name = "pragma-org/amaru-treasury"
version = "1.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'pragma-org/amaru-treasury'"

[repository]
user = "pragma-org"
project = "amaru-scopes-management"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "SundaeSwap-finance/aicone"
version = "504e1049abefdaf40f294a1b94a57d236717abc6"
source = "github"

[[dependencies]]
name = "SundaeSwap-finance/treasury-contracts"
version = "8a3183c929be57886214624b45ee0c43a0c19277"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"

[config.default]
# The name of the scopes token.
scopes_token_name = "amaru 2026 scopes"

# Expiration time (POSIX time in *milliseconds*). Currently set to 31st Dec 2026, 23:59:59 GMT
expiration = 1798757999000

# PRAGMA's general assembly members verification key hashes.
pragma_general_assembly = [
  { bytes = "9a296a8571c597459b54ddc515668c2cd357bec3284413f4d92c67fd", encoding = "base16" },
  { bytes = "d3fcffe0f00fdb109674a16891cdc2c94cfd5147dc89df200169bdd8", encoding = "base16" },
  { bytes = "e0b68e229f9c043ab610067ed7f3c6d662b8f3c6bb4ec452c11f6411", encoding = "base16" },
  { bytes = "7095faf3d48d582fbae8b3f2e726670d7a35e2400c783d992bbdeffb", encoding = "base16" },
  { bytes = "058a5ab0c66647dcce82d7244f80bfea41ba76c7c9ccaf86a41b00fe", encoding = "base16" },
]

[config.preview]
# The name of the scopes token.
scopes_token_name = "amaru 2026 scopes"

# Expiration time (POSIX time in *milliseconds*). Currently set to 31st Dec 2026, 23:59:59 GMT
expiration = 1798757999000

# PRAGMA's general assembly members verification key hashes.
pragma_general_assembly = [
  { bytes = "7095faf3d48d582fbae8b3f2e726670d7a35e2400c783d992bbdeffb", encoding = "base16" },
]
